// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleWebApiDotNetCore.Data;

#nullable disable

namespace SampleWebApiDotNetCore.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    [Migration("20250720034727_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleWebApiDotNetCore.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "AAA",
                            Title = "tesT",
                            YearPublished = 1991
                        },
                        new
                        {
                            Id = 2,
                            Author = "BBB",
                            Title = "tesT2",
                            YearPublished = 1993
                        },
                        new
                        {
                            Id = 3,
                            Author = "CCC",
                            Title = "tesT3",
                            YearPublished = 1945
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
